name: Run Unit Test

on:
  push:
    branches: [master, dev]
jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@master

    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 20.x

    - name: Install dependencies
      run: yarn install

    - name: Run unit test
      run: yarn test -- --watchAll=false
